### ISSUE TITLE
Mod needed to install...

### ISSUE THREAD

**Issue by MatthewPaulGithub** [previousnext/redmine_boards_watchers#12]
I was getting an error thrown when trying to install - it was looking for a record in messages with an id='all' - so I made a minor mod as follows -

/opt/bitnami/apps/redmine/htdocs/plugins/redmine_boards_watchers/db/migrate/0002_update_message_sticky_priority

old

    Message.find(:all).each do |msg|

new

    Message.all.each do |msg|

which seemed to work. But bear in mind that a) I don't have any messages to start and b) I don't know what the heck I'm doing, not a ruby expert, just guessing really. But thought I'd log this here for others...

**Comment by kimpepper** [comment]
Thanks @MatthewPaulGithub What version of redmine did you test this against?

**Comment by MatthewPaulGithub** [comment]
Oh, sorry, I should have put that in originally - it's the latest bitnami stack - redmine 3.4 -

Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

And again, I don't know ruby, that mod I made was just because when I did the migrate, it was giving me an error on that file trying to do the update, so I googled a different way of going through each record, which I figured it was doing to convert any existing messages.  Normally I would have just given up at the first hurdle, but this seemed like such a good plugin and good functionality that I thought I'd give it a go.  Thanks for developing this, it's excellent...

**Comment by cmrd-senya** [comment]
I confirm, the change described by the topic starter is required to use the plugin with recent redmine versions.

Here is a commit (not by me) which includes the changes to make it work properly: https://github.com/takaosan/redmine_boards_watchers/commit/92859489965e19e080827121cf2a6c309a872b1a
